### ISSUE TITLE
Looking into Text-Files

### ISSUE THREAD

**Issue by equaliser0** [tfeldmann/organize#17] opened 2018-10-05 09:38 UTC
I wondering about integrating the function to look into textfiles to filter like

```
if 'blabla' in open('example.txt').read():
    print("true")
```

This could be very useful for i.e. letters like machine-readable pdfs or so.

**Comment by tfeldmann** [comment] 2018-10-05 09:39
Yes, this is useful for sure and something I'm working on. Duplicate of #10

**Closed** 2018-10-05 09:40 UTC
