### ISSUE TITLE
can I move matched folder to trash?

### ISSUE THREAD

**Issue by TYZRPVX** [tfeldmann/organize#50] opened 2019-10-17 12:53 UTC
I try Regex to match folder name, but failed. Maybe this tool only cares about files not folder?

**Comment by tfeldmann** [comment] 2019-11-26 15:34
At the moment this tool only targets files, not folders. Support for folders is planned but it is a tough nut to crack while not breaking existing config files. (This can be something for version 2).

I'm closing this because it is a duplicate of #25

**Closed by tfeldmann** 2019-11-26 15:34 UTC
