### ISSUE TITLE
[Trash] ERROR! File not found

### ISSUE THREAD

**Issue by gregoriopellegrino** [tfeldmann/organize#38] opened 2019-06-27 16:07 UTC
Hi,
thanks for this software. I run it at every login, for cleaning the Downloads folder, but when a file is moved to the trash i get this error:

`[Trash] ERROR! File not found`

**Comment by tfeldmann** [comment] 2019-06-27 18:01
Hi! Can you post your config file here? I can‘t tell what’s wrong from this error message.

**Comment by gregoriopellegrino** [comment] 2019-06-27 18:22
Here you have:
```
rules:
    # move incomplete downloads older > 7 days into the trash
    - folders:
        - ~/Downloads
      filters:
        - LastModified:
            days: 7
      actions:
        - Trash
```

**Comment by tfeldmann** [comment] 2019-06-27 21:25
Ok this looks simple. I‘ll look into it. Which version of organize do you use?

**Comment by gregoriopellegrino** [comment] 2019-06-28 06:24
version 1.4.3

**Comment by tfeldmann** [comment] 2019-06-28 07:38
I cannot reproduce this and need some more info.

- Is this your full config file or are you doing anything else with the download folder?
- Which operating system are you using?
-  Can you post the full outputs of `organize sim` and `organize run`?

**Comment by gregoriopellegrino** [comment] 2019-06-28 10:25
I run it at the login on MacOs 10.14.5 using a .command file, that is:

```
#!/bin/bash
export PATH=/usr/local/bin:$PATH
organize run
```

**Comment by tfeldmann** [comment] 2019-07-02 12:37
Does this happen if you run `PATH=/usr/local/bin:$PATH organize run` in the terminal?

**Comment by gregoriopellegrino** [comment] 2019-07-02 12:47
No, I think it is an owner problem

**Comment by tfeldmann** [comment] 2022-02-07 14:18
Closing this issue because this is a setup problem I cannot reproduce. Please reopen if it is still not working

**Closed by tfeldmann** 2022-02-07 14:18 UTC
