### ISSUE TITLE
startswith doesn't work with accents

### ISSUE THREAD

**Issue by misterio2051** [tfeldmann/organize#74] opened 2020-04-11 12:56 UTC
As the title says. I have the following rule:

```yaml
# Cálculo PDF
rules:
  - folders: ~/Google Drive/
    subfolders: false
    filters:
      - extension:
         - pdf
      - filename:
          startswith: Cálculo 
    actions:
      - move: "~/Google Drive/Escuela/12vo/Cálculo Integral/Periodo #6/PDF's/"
```
I've tried adding quotations to the startswith argument but it still doesn't work.

**Comment by tfeldmann** [comment] 2020-04-30 16:57
I just created a unit test but could not reproduce this.
My guess is that this is related to #40 and the accents are encoded differently. You could try to copy the á from your filename directly into the script, but this is just a workaround.

**Comment by tfeldmann** [comment] 2022-08-17 17:27
Closing this as duplicate of #40.

**Closed by tfeldmann** 2022-08-17 17:27 UTC
Labels: bug, duplicate
