### ISSUE TITLE
Error installing organize-tool[textract] with pipx `extract-msg (<=0.29.*)` and workaround

### ISSUE THREAD

**Issue by kwbr** [tfeldmann/organize#283] opened 2023-06-02 12:00 UTC
With the current version 2.4.0 it is not possible to install the package via PyPi using pipx:

```
  File "/usr/lib/python3/dist-packages/pipx/venv_inspect.py", line 54, in get_package_dependencies
    for req in map(Requirement, dist.requires or []):
  File "/usr/lib/python3/dist-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    extract-msg (<=0.29.*)

```

This is an issue with a change in the `wheel` package. See for example: https://github.com/deanmalmgren/textract/issues/461

As a workaround one can first install `organize-tool` and then manually install a newer version of `textract`. This works for me.

```
pipx install organize-tool
pipx runpip organize-tool install textract==1.6.5
```

Happy and heavy user of the tool. :heart:

**Comment by tfeldmann** [comment] 2023-06-02 13:40
Hey thanks for the heart!
I can reproduce this, but I'm not yet sure how to fix this. Maybe pinning `wheel` to an older version?

Let me know if you have a good solution. I'll try some things in the next days.

**Comment by kwbr** [comment] 2023-06-03 07:55
It's strange that installing `textract` separately works. I am not sure how to solve this. I tried debugging this further but following pip installing a package is quiet hard. Others seem to have tried to pin `wheel` to an older version. Hopefully `textract` will release an update with a change to the `extract-msg` dependency.

Also installing with pip into a venv also works. So maybe it's a problem with pipx.

**Comment by lensaffair** [comment] 2023-06-26 06:57
Not sure if this is related; but after upgrading to Python 3.11.3, I cannot install ``organize-tool[texttract]`` either using ``pip``. Error seems very weird to me:

```
pip install organize-tool[textract]
zsh: no matches found: organize-tool[textract]
```

**Comment by gaby** [comment] 2023-07-01 02:14
@lensaffair Could it be related to the project not listing py3.11 as supported on Pypi? https://pypi.org/project/organize-tool/

**Comment by gaby** [comment] 2023-07-01 02:26
@tfeldmann @lensaffair I just submitted a PR that adds py3.11 to the pyproject file and the unit-tests.

**Comment by kamuridesu** [comment] 2023-08-03 17:25
> Not sure if this is related; but after upgrading to Python 3.11.3, I cannot install `organize-tool[texttract]` either using `pip`. Error seems very weird to me:
> 
> ```
> pip install organize-tool[textract]
> zsh: no matches found: organize-tool[textract]
> ```

The issue is that zsh considers `[]` as part of it's syntax instead of passing the arguments to pip. Try to quote it so it's consider a string:

```
pip install "organize-tool[texttract]"
```

**Comment by lensaffair** [comment] 2023-08-03 17:48
That's it - works like a charm. Thanks a lot!

**Comment by tfeldmann** [comment] 2024-01-07 11:08
This should be fixed with v3.

**Closed by tfeldmann** 2024-01-07 11:08 UTC
Labels: bug
